### ISSUE TITLE
compatibility with the zero

### ISSUE THREAD

**Issue by rcullito** [davidbkemp/KeyboardCombinerArduinoSketch#2]
Hello David!

I noticed that the README suggests that this example is not compatible with the zero while the instructions.md suggest it is possible. It looks like the host shield repo has a branch for the zero at https://github.com/felis/USB_Host_Shield_2.0/tree/Zero?

Are there any updates on how best to use your code against this branch?

Thanks,
Rob

**Comment by davidbkemp** [comment]
Sorry, but I haven't tried out the Zero branch. I must update those instructions. You should try a Leonardo instead. They seem to still be available.

Sometime in the last two or three years there have been some changes to the shield library code that make the whole thing more temperamental. The whole management of USB hubs doesn't always work properly. Depending on your set up, I find that you have to either modify the number of hubs declared in my code, or play around with connecting the keyboard before connecting the pedals. The shield library code is quite hard to read and so I'm struggling to figure out what the problem is.

This is just a little weekend project for me, and I haven't had much time to figure out what's going wrong. Hopefully I'll have some time soon.

**Comment by rcullito** [comment]
Thanks for getting back to me so quickly David! And yes I hear you on the struggles of integrating with third party code. Will poke around from my end too with regards to the zero. Was very excited to come across your project so appreciate you getting it out there.
